version: '1.0.0-pre{build}'
branches:
  only:
    - master
image: Visual Studio 2017
install:
  - nuget restore
configuration: Debug
before_build:
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Core\Core.csproj"
      $xml = [xml](get-content $xmlPath)
      $propertyGroup = $xml.Project.PropertyGroup | Where { $_.Version}
      $propertyGroup.Version = $env:appveyor_build_version
      $xml.Save($xmlPath)
after_build:
  - ps: Get-ChildItem .\Core\bin\Debug\Vostok.Core.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
