version: '1.0.0-pre{build}'
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
install:
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Vostok.Airlock.Client\Vostok.Airlock.Client.csproj"
      $xml = [xml](get-content $xmlPath)
      $version = $xml.CreateElement("Version")
      $versionText = $xml.CreateTextNode($env:appveyor_build_version)
      $version.AppendChild($versionText)
      $xml.Project.PropertyGroup.AppendChild($version)
      $xml.Save($xmlPath)
  - dotnet restore
configuration: Release
after_build:
  - ps: if ($env:appveyor_repo_branch -eq "master") { Get-ChildItem $env:appveyor_build_folder\Vostok.Airlock.Client\bin\Release\Vostok.Airlock.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } }
test_script:
  - ps: dotnet test "$env:appveyor_build_folder\Vostok.Airlock.Client.Tests\Vostok.Airlock.Client.Tests.csproj" --logger "trx;LogFileName=airlock-client-tests.trx"
after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:appveyor_job_id)", "$env:appveyor_build_folder\Vostok.Airlock.Client.Tests\TestResults\airlock-client-tests.trx")
