version: '1.0.0-pre{build}'
image: Visual Studio 2017
install:
  - nuget sources add -name core -source https://ci.appveyor.com/nuget/core-2nbdf5dfgymf
  - dotnet restore
configuration: Release
before_build:
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Vostok.ClusterClient\Vostok.ClusterClient.csproj"
      $xml = [xml](get-content $xmlPath)
      $version = $xml.CreateElement("Version")
      $versionText = $xml.CreateTextNode($env:appveyor_build_version)
      $version.AppendChild($versionText)
      $xml.Project.PropertyGroup.AppendChild($version)
      $xml.Save($xmlPath)
  - ps: |
      $zeroPaddedBuildNumber = [convert]::ToInt32($env:appveyor_build_number, 10).ToString("000000")
      Update-AppveyorBuild -Version "1.0.0-pre$zeroPaddedBuildNumber"
      $xmlPath = "$env:appveyor_build_folder\Vostok.ClusterClient.Transport.Http\Vostok.ClusterClient.Transport.Http.csproj"
      $xml = [xml](get-content $xmlPath)
      $version = $xml.CreateElement("Version")
      $versionText = $xml.CreateTextNode($env:appveyor_build_version)
      $version.AppendChild($versionText)
      $xml.Project.PropertyGroup.AppendChild($version)
      $xml.Save($xmlPath)
after_build:
  - ps: if ($env:appveyor_repo_branch -eq "master") { Get-ChildItem $env:appveyor_build_folder\Vostok.ClusterClient\bin\Release\Vostok.ClusterClient.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } }
  - ps: if ($env:appveyor_repo_branch -eq "master") { Get-ChildItem $env:appveyor_build_folder\Vostok.ClusterClient.Transport.Http\bin\Release\Vostok.ClusterClient.Transport.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } }
test_script:
  - ps: dotnet test "$env:appveyor_build_folder\Vostok.ClusterClient.Tests\Vostok.ClusterClient.Tests.csproj" --logger "trx;LogFileName=clusterclient-tests.trx"
after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:appveyor_job_id)", "$env:appveyor_build_folder\Vostok.ClusterClient.Tests\TestResults\clusterclient-tests.trx")
